// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "TrakLogik Home", "traklogik home is research amp development companylocated in san diego ca and bangor me we develop advanced algorithms applications forcharacterizing recognizing patterns digital data includes video audio hyper spectral medicaltest ethernet packets are implemented software hardware you welcome to work with us as customer or partner if have challenging pattern recognitiontasks would like see results within fewmonths weeks typically the challenge massive amount of dataand diversity target specialize dealing such problems llp about nbsp management partners projects solutions wine spectroscopy bio medical analysis packet manager tracking plankton recognition contact copyright by corporation all rights reserved http www com ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("about.html", "TrakLogik About", "traklogik about is small research amp development company located in san diego ca and bangor maine was started california with the idea of applying advanced mathematical solutions that require non trivial data analysis implementing these on parallel hardware for real time processing nbsp we opened major branch management llp home us partners projects wine spectroscopy bio medical ethernet packet manager video target tracking plankton recognition contact partnerships alliances dr marina murzina founder president cto oftraklogik she has ph theoretical astrophysics thesis quot self similar theory collapsing stars supernova explosions physics diploma honor from moscow stateuniversity specializing neutrino supernovaexplosions structure shock waves collapsingstars plasma nuclear copyright by corporation all rights reserved http www com natalia abramova co ceo her academic background molecular genetics biotechnology registered vendor forthe university providingmathematical medicaldata closely works themaine technology institute won grant developing anfpga encryptor also set new projectsrelated to patent filing a2tech italy developes cutting edgetechnologies aerial surveillance uav design provided videodata applications weare collaborating hypr spectral patternrecognition our latest project analyzingdata department vettechnology mainein augusta security network provides supportto cyber mission networkis advance “fosteringinnovation through collaboration” worldwide worked as senior scientist at theinstitute experimental inmoscow virginia newyork stony brook served head mathematics group atomnigon technologies inc mining logical algebra graph clustering context basedrepresentation spaces scientistat brookhaven nuclearresonance isomers chief atappserver led researchand hyper spectralimaging radio frequencyanalysis finding white wi fi radios andnetwork optimization imageprocessing methods avariable bit width fpga super dsp published more than scientific papers themajor journals europe servedas principal investigator dod sbir projecthyperspectral cube processor high speed efficiency implemented an platform ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("solutions.html", "TrakLogik Solutions", "traklogik solutions spectral analysis of winesand juices features wines are directly related to their degustation properties aaawe develop database signatures along with the algorithms for findingwines that close in taste goal is help winemakers inform theirclients about favorite tasting and wine consumers find differentfoods moods llp home nbsp us management partners projects amp spectroscopy bio medical data ethernet packet manager video target tracking plankton recognition contact copyright by corporation all rights reserved http www com developing compact stand alone fpga basedethernet enable our customers re route modify packets exactly way they desire analyzed patterns interest addresses keywords making decisions suchas encryption routing blocking changing contents we implement standard type lower withproprietary because design device cannot be intruded also system invisible on network encryptor october has won tech start grant maine technology institute super securefpga based patent now pending engineering team isdeveloping custom fully customizable standalone compactfpga security good partner educating aboutlatest events cyber helping findingpartners miningand statistical performs biological research particularly specialize situations where not or methods do give immediate results registered vendor forthe university providingmathematical medicaldata apply new perform computations produce plots tables deliver reports can embedded into customer publication latest project analyzing department vet augusta aerial videos under water images car small green red rectangle highway seen as pixel object movie was taken from fixed wing evektor sportstar italy a2tech challenges this application extremely ever non uniform color disappears loss resolution when obscured bridges requires very precise image stabilization even movements board camera cause shifts bigger than there many similar looking objects view since poorly resolved been partly developed appserver inc works software ported hardware an exclusive license provided bellamare llc novel identifyingplankton species underwater due high diversity conditions challenge conventionalpattern date most annotations have done manually offers great opportunities environmental marine science impactassessments fishing industry references situ imaging cousin murzina presentation at maritime alliance nov press release quot monitoring count identify sea news please click picture watch ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("wine01.html", "wine01", "wine01 spectral features of wines aredirectly related to their degustationproperties aaawe develop database spectralsignatures analysis and juices more ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fpga01.html", "fpga01", "fpga01 in october traklogik has wona tech start grant with maine technology institute for patenting asuper secure fpga based ethernetpacket manager more ethernet packet amp encryptor ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("cats01.html", "cats01", "cats01 bio medical data miningand statistical analysis traklogik is registered vendor for the university of maine providing mathematical more ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("target01_pic.html", "target01", "target01 target tracking in aerial and under water videos traklogik has developed set of algorithms applications for objects underwater hyper spectralimages more ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("target_02a_pic_for_flv.html", "target_02a_pic_for_flv", "target pic for flv click picture to play video ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("target_02b_flv_Effigy.html", "target_02b_flv_Effigy", "target flv effigy ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("contact.html", "TrakLogik Contact", "traklogik contact please us at llp home about nbsp management partners projects amp solutions wine spectroscopy bio medical data analysis ethernet packet manager video target tracking plankton recognition copyright by corporation all rights reserved http www com ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("target_02c_flv_player_Jeroen.html", "get_02c_flv_player_Jeroen", "get flv player jeroen flvplayer requires javascript and the latest flash here ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("target01_flash_movie.html", "target01", "target01 target tracking in aerial and under water videos traklogik has developed set of algorithms applications for objects underwater hyper spectral images more ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("trackfire.html", "TrakLogik TrackFire Main", "traklogik trackfire main fire images llp home about nbsp us management partners projects amp solutions wine spectroscopy bio medical data analysis ethernet packet manager video target tracking plankton recognition contact copyright by corporation all rights reserved http www com original image looks relatively dim compared to the view of town same after color transformation can be seen as bright spots and lights city transformations is most distinguishable object yellow grass distinguished from clips smoke manavgat raw avi quot save shows forest how starts at th second progresses taken signal ee bilkent edu tr visifire or watch beginning this clip loading ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fire/index.html", "TrakLogik TrackFire Main", "traklogik trackfire main fire images nbsp copyright by corporation all rights reserved http www com original image looks relatively dim compared to the view of town same after color transformation can be seen as bright spots and lights city transformations is most distinguishable object yellow grass distinguished from video clips smoke manavgat raw avi quot save target shows forest how starts at th second progresses taken signal ee bilkent edu tr visifire or watch beginning this clip loading llp home about us management partners projects amp solutions wine spectroscopy bio medical data analysis ethernet packet manager tracking plankton recognition contact ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fire/live_stream_file.html", "TrakLogik TrackFire Main", "traklogik trackfire main llp home about nbsp us management partners projects amp solutions wine spectroscopy bio medical data analysis ethernet packet manager video target tracking plankton recognition contact copyright by corporation all rights reserved http www com vod html?src secaucus nj fire department multiple alarm brush lt href quot gt ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fire/change_pic.html", "Untitled Page", "untitled page changingpic jpg ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fire/livestream_text_placeholder.html", "Untitled Page", "untitled page computational nbsp results ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fire/show.html", "Untitled Page", "untitled page computational nbsp results ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   this[database_length++] = new SearchPage("fire/slideshow.html", "Untitled Page", "untitled page ", "TrakLogik Company Website  State of the Art Pattern Rrecognition");
   return this;
}
